name: Check event payload
on:
  issues:
    types: [opened, assigned, unassigned, labeled, unlabeled]
  issue_comment:
    types: [created]
    
jobs:
  print_payload:
    runs-on: ubuntu-latest
    steps:
      - name: print
        env:
          GH_EVENT: ${{ toJSON(github.event) }}
          JOIN_DATA: ${{ join(github.event.issue.labels.*.name) }}
        shell: bash
        run: |
          echo $GH_EVENT
          echo $JOIN_DATA
